---
title: "A3_3"
author: "Group4"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sandwich)
library(plm)
library(lmtest)
library(stargazer)
library(tidyverse)
library(knitr)
library(car)
library(readr)
library(dplyr)

VTED16 <- read.csv("~/Documents/Brandeis/Healthcare Data Analytics/Assignment3/VTED16.TXT")
View(VTED16)

# select first three letters in DX1-DX29
as.factor(VTED16[,10:29])
VTED16_TX <- VTED16
VTED16_TX[,10:29] <- lapply(VTED16[,10:29], function(x)substr(x,1,3))
View(VTED16_TX)

# select T40xxxx, T41xxxx, T42xxxx, and T43xxxx
VTED16_TX_3 <- VTED16_TX %>% filter(rowMeans(VTED16_TX[,10:29] == "T40")>0 | rowMeans(VTED16_TX[,10:29] == "T41") > 0|rowMeans(VTED16_TX[,10:29] == "T42") > 0 | rowMeans(VTED16_TX[,10:29] == "T43") > 0)
View(VTED16_TX_3)

#1 How many ED visits exactly have been diagnosed as drug user/abuser? 
length(unique(VTED16_TX_3$UNIQ))
```


 
```{r}
#2 There is a myth that the drug use/abuse has been a male problem and that women have much better protection measures to stay away from drug use/abuse let alone overdoses severe enough that lead to an ED admission. Can you check if your data supports this gender bias myth? 
male = count(VTED16_TX_3 %>% filter(sex == 1))
male
female = count(VTED16_TX_3 %>% filter(sex == 2))
female
```

```{r}
#3 Tens of millions of dollars reportedly were spent on drug use related cases that year alone. Can you find the exact dollar amount for your identified patients in this question? Of the three insurances in Question 2, what was share of each of the total payments?
VTED16_TX_3_spend = tapply(VTED16_TX_3$CHRGS,VTED16_TX_3$PPAY ,sum)
VTED16_TX_3_spend
total_spend = sum(VTED16_TX_3$CHRGS) 
total_spend
share_medicare = VTED16_TX_3_spend[2]/total_spend
share_medicaid = VTED16_TX_3_spend[3]/total_spend
share_commercial_payers= (VTED16_TX_3_spend[6]+VTED16_TX_3_spend[7])/total_spend
share_insurance = data.frame(variable = c('share_medicare','share_medicaid','share_commercial_payers'),
      value = c(share_medicare,share_medicaid,share_commercial_payers))
```

```{r}
# 4
ed_drug = merge(VTED16_TX_3, VTED16, all.x = TRUE, by =  'UNIQ')
ed_drug = data.table(ed_drug)
data_drug_abuse = ed_drug[, -c(2:70)]

er_visits = ed_drug[, .N]
row_index = vector()
for (i in 1:nrow(data_drug_abuse)){
  if (any(startsWith(as.character(data_drug_abuse[i,11:30]),"T404"))|
      any(startsWith(as.character(data_drug_abuse[i,11:30]),"T4362"))) {
    row_index = c(row_index,i)
  }  
}
sn = data_drug_abuse[row_index,]
View(sn)

sn = data.table(sn)
male = sn[sex.y == 1]
View(sn[max(pdays.y)])
```


```{r}
#5 Name the 3 zip code regions with the highest numbers of drug use/abuse cases.
as.factor(VTED16_TX_3$TXTZIP)
VTED16_TX_3_ZIP <- VTED16_TX_3 %>% group_by(TXTZIP) %>% summarise(count = n()) %>% arrange(-count)
VTED16_TX_3_ZIP[1:3,]
```


```{r}
#6 What are the 10 most common diagnoses of drug use/abuse?
merge_table <- merge(VTED16, VTED16_TX_3, by = "UNIQ")
merge_table_new <- merge_table[,11:30]
View(merge_table_new)
# count number
code_frequency <- table(unlist(merge_table_new))
code_frequency <- data.frame(code_frequency)
View(code_frequency)
# select useful rows
as.factor(code_frequency$Var1)
code_frequency_t <- code_frequency %>% filter((substring(code_frequency$Var1,1,3) == "T40") > 0 | (substring(code_frequency$Var1,1,3) == "T41") > 0 | (substring(code_frequency$Var1,1,3) == "T42") > 0 | (substring(code_frequency$Var1,1,3) == "T43") > 0) %>% arrange(-Freq)
head(code_frequency_t, 10)
```


